#快捷潜影盒配置
quickshulker:
  #可以打开潜影盒
  can_open_shulker: true
  #可以打开工作台
  can_open_Workbench: true
  #可以打开末影箱
  can_open_enderchest: true
  #可以打开锻造台
  can_open_smithingTable: true
  #可以打开切石机
  can_open_stonecutter: true